-- =============================================================================
-- نظام إدارة المطبخ الداخلي - سكريبت إنشاء الجداول والقيود والعروض (DDL)
-- Indoor Kitchen Management System - DB Schema (DDL)
-- =============================================================================

PROMPT Dropping existing tables and views if they exist...
BEGIN
  FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'ORDER_STATUS_HISTORY', 'ORDER_CUSTOMIZATIONS', 'ORDER_ITEMS', 'ORDERS', 
    'DELIVERY_PARTNERS', 'CUSTOMERS', 'RECIPE_INGREDIENTS', 'RECIPES', 
    'INVENTORY_BATCHES', 'UOM_CONVERSIONS', 'INGREDIENTS'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

BEGIN
  FOR r IN (SELECT view_name FROM user_views WHERE view_name IN ('V_ACTIVE_MENU', 'V_MENU_CUSTOMIZATIONS')) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || r.view_name;
  END LOOP;
END;
/

-- 1. جدول المكونات الخام (Ingredients)
PROMPT Creating INGREDIENTS table...
CREATE TABLE ingredients (
    ingredient_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name              VARCHAR2(150) NOT NULL,
    base_uom          VARCHAR2(20) NOT NULL, -- جرام، ملي، قطعة، إلخ.
    min_stock_level   NUMBER DEFAULT 0 NOT NULL,
    current_cost      NUMBER(10,2) DEFAULT 0.00 NOT NULL, -- يتم تحديثه بناءً على آخر سعر شراء
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_ingredients PRIMARY KEY (ingredient_id),
    CONSTRAINT uq_ingredient_name UNIQUE (name)
);

-- 2. جدول التحويل بين وحدات القياس (UOM Conversions)
PROMPT Creating UOM_CONVERSIONS table...
CREATE TABLE uom_conversions (
    from_uom           VARCHAR2(20) NOT NULL,
    to_uom             VARCHAR2(20) NOT NULL,
    conversion_factor  NUMBER(15,6) NOT NULL, -- معامل الضرب للتحويل من الوحدة الكبرى للصغرى (كيلو إلى جرام = 1000)
    CONSTRAINT pk_uom_conversions PRIMARY KEY (from_uom, to_uom)
);

-- 3. جدول دفعات المخزون (Inventory Batches) لتتبع FIFO وتاريخ الصلاحية
PROMPT Creating INVENTORY_BATCHES table...
CREATE TABLE inventory_batches (
    batch_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ingredient_id     NUMBER NOT NULL,
    purchase_date     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    expiry_date       DATE NOT NULL,
    initial_qty       NUMBER(12,3) NOT NULL,
    remaining_qty     NUMBER(12,3) NOT NULL,
    unit_cost         NUMBER(10,2) NOT NULL, -- تكلفة الشراء الفعلية لهذه الدفعة
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_inventory_batches PRIMARY KEY (batch_id),
    CONSTRAINT fk_batch_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE CASCADE,
    CONSTRAINT chk_batch_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_batch_qty CHECK (remaining_qty >= 0)
);

-- 4. جدول الوجبات والوصفات الفرعية (Recipes & Menu)
PROMPT Creating RECIPES table...
CREATE TABLE recipes (
    recipe_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name              VARCHAR2(150) NOT NULL,
    description       VARCHAR2(500),
    selling_price     NUMBER(10,2) DEFAULT 0.00 NOT NULL, -- سعر البيع النهائي للمستهلك (0 إذا كانت وصفة فرعية)
    image_url         VARCHAR2(255),
    is_sub_recipe     CHAR(1) DEFAULT 'N' NOT NULL, -- نعم إذا كانت وصفة تحضيرية/فرعية (مثل صلصة طماطم)
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_recipes PRIMARY KEY (recipe_id),
    CONSTRAINT uq_recipe_name UNIQUE (name),
    CONSTRAINT chk_recipe_sub CHECK (is_sub_recipe IN ('Y', 'N')),
    CONSTRAINT chk_recipe_active CHECK (is_active IN ('Y', 'N'))
);

-- 5. جدول تفاصيل مكونات الوصفات (Recipe Ingredients - BOM)
PROMPT Creating RECIPE_INGREDIENTS table...
CREATE TABLE recipe_ingredients (
    recipe_ingredient_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    recipe_id             NUMBER NOT NULL, -- الوجبة أو الوصفة الفرعية الحالية
    ingredient_id         NUMBER,          -- المادة الخام المستعملة (NULL إذا كانت وصفة فرعية)
    sub_recipe_id         NUMBER,          -- الوصفة الفرعية المستعملة (NULL إذا كانت مادة خام)
    quantity              NUMBER(12,3) NOT NULL, -- الكمية المطلوبة
    uom                   VARCHAR2(20) NOT NULL,  -- الوحدة المستخدمة في الوصفة (يجب أن تتطابق أو يوجد تحويل لها)
    CONSTRAINT pk_recipe_ingredients PRIMARY KEY (recipe_ingredient_id),
    CONSTRAINT fk_ri_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_ri_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE CASCADE,
    CONSTRAINT fk_ri_sub_recipe FOREIGN KEY (sub_recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT chk_ri_type CHECK (
        (ingredient_id IS NOT NULL AND sub_recipe_id IS NULL) OR 
        (ingredient_id IS NULL AND sub_recipe_id IS NOT NULL)
    )
);

-- 6. جدول العملاء (Customers)
PROMPT Creating CUSTOMERS table...
CREATE TABLE customers (
    customer_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name              VARCHAR2(150) NOT NULL,
    phone             VARCHAR2(20) NOT NULL,
    email             VARCHAR2(150),
    address           VARCHAR2(300) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_phone UNIQUE (phone)
);

-- 7. جدول شركات التوصيل (Delivery Partners)
PROMPT Creating DELIVERY_PARTNERS table...
CREATE TABLE delivery_partners (
    partner_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name              VARCHAR2(150) NOT NULL,
    contact_number    VARCHAR2(20),
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_delivery_partners PRIMARY KEY (partner_id),
    CONSTRAINT chk_dp_active CHECK (is_active IN ('Y', 'N'))
);

-- 8. جدول الطلبات الرئيسي (Orders)
PROMPT Creating ORDERS table...
CREATE TABLE orders (
    order_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id         NUMBER NOT NULL,
    order_date          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status              VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    order_type          VARCHAR2(20) NOT NULL, -- DELIVERY / PICKUP
    delivery_partner_id NUMBER,
    total_amount        NUMBER(10,2) NOT NULL,
    payment_method      VARCHAR2(30) NOT NULL, -- COD / INSTAPAY / WALLET
    payment_reference   VARCHAR2(100), -- مرجع التحويل للمدفوعات الإلكترونية
    created_by          VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_USER') NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_order_partner FOREIGN KEY (delivery_partner_id) REFERENCES delivery_partners (partner_id),
    CONSTRAINT chk_order_status CHECK (status IN ('PENDING', 'PREPARING', 'READY', 'DELIVERED')),
    CONSTRAINT chk_order_type CHECK (order_type IN ('DELIVERY', 'PICKUP')),
    CONSTRAINT chk_order_payment CHECK (payment_method IN ('COD', 'INSTAPAY', 'WALLET'))
);

-- 9. جدول تفاصيل الطلبات (Order Items)
PROMPT Creating ORDER_ITEMS table...
CREATE TABLE order_items (
    order_item_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id          NUMBER NOT NULL,
    recipe_id         NUMBER NOT NULL,
    quantity          NUMBER(5) NOT NULL,
    unit_price        NUMBER(10,2) NOT NULL,
    actual_cost       NUMBER(10,2), -- التكلفة الفعلية وقت تنفيذ الطلب (لحسابات الربحية التاريخية)
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_oi_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id)
);

-- 10. جدول تعديلات الوجبات (Order Customizations)
PROMPT Creating ORDER_CUSTOMIZATIONS table...
CREATE TABLE order_customizations (
    customization_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_item_id      NUMBER NOT NULL,
    customization_name VARCHAR2(150) NOT NULL, -- بدون بصل، جبنة إضافية، إلخ.
    charge_amount      NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT pk_order_customizations PRIMARY KEY (customization_id),
    CONSTRAINT fk_oc_item FOREIGN KEY (order_item_id) REFERENCES order_items (order_item_id) ON DELETE CASCADE
);

-- 11. جدول سجل تتبع حالات الطلب (Order Status History)
PROMPT Creating ORDER_STATUS_HISTORY table...
CREATE TABLE order_status_history (
    history_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id          NUMBER NOT NULL,
    status            VARCHAR2(30) NOT NULL,
    changed_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by        VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_USER') NOT NULL,
    CONSTRAINT pk_order_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE
);

-- =============================================================================
-- إنشاء الفهارس (Indexes) لتحسين الأداء
-- =============================================================================
PROMPT Creating Indexes...
CREATE INDEX idx_ib_ingredient ON inventory_batches(ingredient_id);
CREATE INDEX idx_ib_expiry ON inventory_batches(expiry_date);
CREATE INDEX idx_ri_recipe ON recipe_ingredients(recipe_id);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_oi_order ON order_items(order_id);

-- =============================================================================
-- إنشاء العروض (Views) المخصصة لبوابة العملاء وتطبيق الصلاحيات
-- =============================================================================
PROMPT Creating Views for Customer Access...

-- عرض الوجبات النشطة الجاهزة للبيع (ليست وصفة فرعية)
CREATE OR REPLACE VIEW v_active_menu AS
SELECT recipe_id, name, description, selling_price, image_url
FROM recipes
WHERE is_active = 'Y' 
  AND is_sub_recipe = 'N';

-- عرض الخيارات الشائعة للتعديل (يمكن اشتقاقها أو وضعها كخيار ثابت)
CREATE OR REPLACE VIEW v_menu_customizations AS
SELECT DISTINCT customization_name, charge_amount
FROM order_customizations
UNION
SELECT 'إضافة جبنة' as customization_name, 15.00 as charge_amount FROM dual
UNION
SELECT 'بدون بصل' as customization_name, 0.00 as charge_amount FROM dual
UNION
SELECT 'سبايسي (حار)' as customization_name, 0.00 as charge_amount FROM dual;

PROMPT Schema DDL Script Created Successfully.
